import type { BusinessTemplate } from "./types";

/**
 * Internal database of UMKM business idea templates.
 * Numbers here are the canonical reference for the financial calculator —
 * AI MUST NEVER invent or override these.
 *
 * marginRange is net margin after operational costs. Product HPP still
 * represents unit-level COGS/gross margin.
 *
 * Categories used for matching:
 *   F&B | Reseller | Jasa | Beauty | Laundry | Digital Product | Retail
 */
export const businessTemplates: BusinessTemplate[] = [
  // ───── F&B ─────────────────────────────────────────────────────────────
  {
    id: "rice-bowl-preorder",
    name: "Rice Bowl Pre-order",
    category: "F&B",
    description:
      "Rice bowl rumahan dengan sistem pre-order via WhatsApp/Instagram untuk area kampus dan perkantoran.",
    minCapital: 3_000_000,
    maxCapital: 10_000_000,
    suitableAreas: ["kampus", "perkantoran", "perumahan"],
    suitableModels: ["online", "pre-order", "dari rumah"],
    suitableAssets: ["bisa masak", "punya dapur"],
    riskLevel: "sedang",
    marginRange: [3, 9],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Chicken Teriyaki Rice Bowl", sellingPrice: 18_000, hpp: 9_500, dailySales: 25 },
      { name: "Spicy Chicken Rice Bowl", sellingPrice: 18_000, hpp: 9_800, dailySales: 20 },
    ],
    capitalItems: [
      { name: "Bahan baku awal", amount: 1_500_000 },
      { name: "Packaging awal", amount: 700_000 },
      { name: "Peralatan tambahan", amount: 1_800_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Gas, listrik, air", amount: 700_000 },
      { name: "Marketing online", amount: 400_000 },
      { name: "Transport/delivery support", amount: 300_000 },
      { name: "Tenaga produksi & owner allowance", amount: 6_800_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "frozen-food-rumahan",
    name: "Frozen Food Rumahan",
    category: "F&B",
    description: "Produksi dan jual frozen food (dimsum, nugget, kebab mini) dari rumah.",
    minCapital: 2_500_000,
    maxCapital: 8_000_000,
    suitableAreas: ["perumahan", "kompleks", "online"],
    suitableModels: ["online", "reseller", "dari rumah"],
    suitableAssets: ["bisa masak", "punya freezer", "punya dapur"],
    riskLevel: "rendah",
    marginRange: [3, 9],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Dimsum Ayam (10 pcs)", sellingPrice: 25_000, hpp: 13_000, dailySales: 15 },
      { name: "Nugget Ayam (500g)", sellingPrice: 30_000, hpp: 17_000, dailySales: 10 },
    ],
    capitalItems: [
      { name: "Bahan baku awal", amount: 1_000_000 },
      { name: "Packaging vacuum", amount: 600_000 },
      { name: "Peralatan tambahan", amount: 1_500_000 },
      { name: "Promosi awal", amount: 400_000 },
      { name: "Dana cadangan", amount: 1_000_000 },
    ],
    monthlyCosts: [
      { name: "Listrik freezer", amount: 350_000 },
      { name: "Gas masak", amount: 250_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Tenaga produksi & stok rusak", amount: 5_900_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },
  {
    id: "kopi-susu-kekinian",
    name: "Kopi Susu Kekinian (Booth)",
    category: "F&B",
    description: "Kopi susu botol/cup di booth dekat keramaian.",
    minCapital: 8_000_000,
    maxCapital: 20_000_000,
    suitableAreas: ["kampus", "perkantoran", "ruko", "pasar"],
    suitableModels: ["offline", "booth", "online"],
    suitableAssets: ["punya kendaraan", "bisa membuat kopi"],
    riskLevel: "sedang",
    marginRange: [3, 9],
    estimatedPaybackMonth: [8, 12],
    products: [
      { name: "Kopi Susu Original", sellingPrice: 15_000, hpp: 7_000, dailySales: 30 },
      { name: "Kopi Aren", sellingPrice: 17_000, hpp: 8_200, dailySales: 25 },
    ],
    capitalItems: [
      { name: "Booth + peralatan", amount: 5_000_000 },
      { name: "Mesin/alat seduh", amount: 3_500_000 },
      { name: "Bahan baku awal", amount: 1_500_000 },
      { name: "Cup + packaging", amount: 800_000 },
      { name: "Promosi awal", amount: 700_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Sewa lapak", amount: 1_000_000 },
      { name: "Listrik & air", amount: 400_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Barista part-time & waste bahan", amount: 8_600_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "jajanan-kaki-lima",
    name: "Jajanan Kaki Lima (Cireng/Cilok)",
    category: "F&B",
    description: "Jajanan murah meriah di gerobak dorong, dekat sekolah/perumahan.",
    minCapital: 2_000_000,
    maxCapital: 6_000_000,
    suitableAreas: ["sekolah", "perumahan", "pasar"],
    suitableModels: ["offline", "gerobak"],
    suitableAssets: ["bisa masak", "punya gerobak"],
    riskLevel: "rendah",
    marginRange: [3, 9],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Cireng Bumbu Rujak (porsi)", sellingPrice: 7_000, hpp: 2_800, dailySales: 40 },
      { name: "Cilok Kuah (porsi)", sellingPrice: 8_000, hpp: 3_200, dailySales: 35 },
    ],
    capitalItems: [
      { name: "Gerobak/etalase", amount: 1_500_000 },
      { name: "Peralatan masak", amount: 800_000 },
      { name: "Bahan baku awal", amount: 600_000 },
      { name: "Packaging", amount: 300_000 },
      { name: "Dana cadangan", amount: 800_000 },
    ],
    monthlyCosts: [
      { name: "Sewa lapak", amount: 400_000 },
      { name: "Gas & bahan bakar", amount: 300_000 },
      { name: "Promosi awal", amount: 150_000 },
      { name: "Tenaga jual harian & waste", amount: 6_800_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },
  {
    id: "catering-sehat",
    name: "Catering Sehat Harian",
    category: "F&B",
    description: "Catering rantangan menu sehat untuk pekerja & ibu rumah tangga.",
    minCapital: 4_000_000,
    maxCapital: 12_000_000,
    suitableAreas: ["perkantoran", "perumahan"],
    suitableModels: ["online", "pre-order", "langganan"],
    suitableAssets: ["bisa masak", "punya dapur", "punya kendaraan"],
    riskLevel: "sedang",
    marginRange: [3, 9],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Paket Sehat Harian", sellingPrice: 25_000, hpp: 16_000, dailySales: 25 },
      { name: "Paket Premium", sellingPrice: 35_000, hpp: 21_000, dailySales: 10 },
    ],
    capitalItems: [
      { name: "Peralatan dapur", amount: 2_000_000 },
      { name: "Bahan baku awal", amount: 1_500_000 },
      { name: "Packaging", amount: 800_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Bahan bakar antar", amount: 700_000 },
      { name: "Gas & listrik", amount: 600_000 },
      { name: "Marketing online", amount: 400_000 },
      { name: "Tenaga masak, kurir & waste", amount: 6_000_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "kue-rumahan",
    name: "Kue & Roti Rumahan",
    category: "F&B",
    description: "Kue kering dan roti homemade untuk pesanan harian / event.",
    minCapital: 2_000_000,
    maxCapital: 7_000_000,
    suitableAreas: ["perumahan", "online"],
    suitableModels: ["online", "pre-order", "dari rumah"],
    suitableAssets: ["bisa membuat kue", "punya oven", "punya dapur"],
    riskLevel: "rendah",
    marginRange: [3, 9],
    estimatedPaybackMonth: [6, 9],
    products: [
      { name: "Roti Manis", sellingPrice: 8_000, hpp: 3_500, dailySales: 30 },
      { name: "Cookies (toples kecil)", sellingPrice: 35_000, hpp: 17_000, dailySales: 5 },
    ],
    capitalItems: [
      { name: "Oven & mixer", amount: 2_500_000 },
      { name: "Bahan baku awal", amount: 800_000 },
      { name: "Packaging", amount: 400_000 },
      { name: "Promosi awal", amount: 300_000 },
      { name: "Dana cadangan", amount: 800_000 },
    ],
    monthlyCosts: [
      { name: "Listrik & gas", amount: 400_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Tenaga produksi & produk gagal", amount: 4_300_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },

  // ───── Reseller ────────────────────────────────────────────────────────
  {
    id: "reseller-fashion-hijab",
    name: "Reseller Fashion Hijab",
    category: "Reseller",
    description: "Reseller hijab dan baju muslim dari supplier grosir, jual via TikTok/Shopee.",
    minCapital: 1_500_000,
    maxCapital: 6_000_000,
    suitableAreas: ["online", "perumahan"],
    suitableModels: ["online", "reseller", "dropship"],
    suitableAssets: ["punya hp", "punya internet", "bisa edit foto"],
    riskLevel: "rendah",
    marginRange: [3, 8],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Hijab Pashmina", sellingPrice: 45_000, hpp: 28_000, dailySales: 8 },
      { name: "Baju Tunik", sellingPrice: 110_000, hpp: 75_000, dailySales: 4 },
    ],
    capitalItems: [
      { name: "Stok awal", amount: 2_500_000 },
      { name: "Packaging", amount: 300_000 },
      { name: "Promosi awal", amount: 700_000 },
      { name: "Dana cadangan", amount: 1_000_000 },
    ],
    monthlyCosts: [
      { name: "Marketing online & ads", amount: 600_000 },
      { name: "Ongkir & packaging", amount: 400_000 },
      { name: "Retur, konten & admin marketplace", amount: 4_800_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },
  {
    id: "reseller-skincare",
    name: "Reseller Skincare Lokal",
    category: "Reseller",
    description: "Distribusi skincare brand lokal via Shopee/TikTok dan referral.",
    minCapital: 2_000_000,
    maxCapital: 8_000_000,
    suitableAreas: ["online", "perumahan", "perkantoran"],
    suitableModels: ["online", "reseller", "dropship"],
    suitableAssets: ["punya hp", "bisa edit konten"],
    riskLevel: "sedang",
    marginRange: [5, 10],
    estimatedPaybackMonth: [2, 5],
    products: [
      { name: "Serum Glow", sellingPrice: 89_000, hpp: 60_000, dailySales: 6 },
      { name: "Sunscreen", sellingPrice: 75_000, hpp: 50_000, dailySales: 8 },
    ],
    capitalItems: [
      { name: "Stok awal", amount: 3_000_000 },
      { name: "Packaging tambahan", amount: 300_000 },
      { name: "Promosi awal", amount: 800_000 },
      { name: "Dana cadangan", amount: 1_000_000 },
    ],
    monthlyCosts: [
      { name: "Marketing online & ads", amount: 700_000 },
      { name: "Ongkir & packaging", amount: 400_000 },
      { name: "Retur, tester & admin marketplace", amount: 6_100_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "dropship-aksesoris",
    name: "Dropship Aksesoris HP",
    category: "Reseller",
    description: "Dropship aksesoris HP (case, charger, holder) tanpa stok besar.",
    minCapital: 500_000,
    maxCapital: 3_000_000,
    suitableAreas: ["online"],
    suitableModels: ["online", "dropship"],
    suitableAssets: ["punya hp", "punya internet"],
    riskLevel: "rendah",
    marginRange: [2, 6],
    estimatedPaybackMonth: [3, 6],
    products: [
      { name: "Case HP", sellingPrice: 35_000, hpp: 22_000, dailySales: 12 },
      { name: "Holder Mobil", sellingPrice: 55_000, hpp: 35_000, dailySales: 5 },
    ],
    capitalItems: [
      { name: "Stok display awal", amount: 800_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 700_000 },
    ],
    monthlyCosts: [
      { name: "Marketing online & ads", amount: 400_000 },
      { name: "Ongkir support", amount: 200_000 },
      { name: "Admin marketplace, retur & konten", amount: 5_200_000 },
      { name: "Biaya tak terduga", amount: 150_000 },
    ],
  },

  // ───── Jasa ────────────────────────────────────────────────────────────
  {
    id: "jasa-cuci-sepatu",
    name: "Jasa Cuci Sepatu",
    category: "Jasa",
    description: "Layanan cuci & repaint sepatu, antar-jemput area kota.",
    minCapital: 1_500_000,
    maxCapital: 5_000_000,
    suitableAreas: ["perumahan", "kampus", "online"],
    suitableModels: ["offline", "online", "dari rumah"],
    suitableAssets: ["telaten", "punya kendaraan"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [1, 3],
    products: [
      { name: "Cuci Standar", sellingPrice: 30_000, hpp: 8_000, dailySales: 8 },
      { name: "Deep Clean", sellingPrice: 60_000, hpp: 18_000, dailySales: 4 },
    ],
    capitalItems: [
      { name: "Peralatan cuci", amount: 1_200_000 },
      { name: "Bahan kimia", amount: 600_000 },
      { name: "Promosi awal", amount: 400_000 },
      { name: "Dana cadangan", amount: 800_000 },
    ],
    monthlyCosts: [
      { name: "Air & listrik", amount: 250_000 },
      { name: "Marketing online", amount: 250_000 },
      { name: "Bahan habis pakai", amount: 300_000 },
      { name: "Tenaga operator & antar-jemput", amount: 5_500_000 },
      { name: "Biaya tak terduga", amount: 150_000 },
    ],
  },
  {
    id: "jasa-cleaning-service",
    name: "Jasa Cleaning Service Rumah",
    category: "Jasa",
    description: "Layanan bersih-bersih rumah harian / mingguan.",
    minCapital: 2_500_000,
    maxCapital: 7_000_000,
    suitableAreas: ["perumahan", "kompleks", "kos"],
    suitableModels: ["offline", "online", "panggilan"],
    suitableAssets: ["telaten", "rajin"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [2, 5],
    products: [
      { name: "Cleaning 2 jam", sellingPrice: 80_000, hpp: 30_000, dailySales: 4 },
      { name: "Deep Cleaning 4 jam", sellingPrice: 200_000, hpp: 90_000, dailySales: 1 },
    ],
    capitalItems: [
      { name: "Peralatan cleaning", amount: 2_000_000 },
      { name: "Bahan kimia awal", amount: 700_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 1_000_000 },
    ],
    monthlyCosts: [
      { name: "Transport", amount: 500_000 },
      { name: "Bahan habis pakai", amount: 400_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Tenaga cleaner lepas", amount: 4_000_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },
  {
    id: "jasa-print-fotokopi",
    name: "Jasa Print & Fotokopi Mahasiswa",
    category: "Jasa",
    description: "Print, fotokopi, jilid skripsi di sekitar kampus.",
    minCapital: 6_000_000,
    maxCapital: 15_000_000,
    suitableAreas: ["kampus", "sekolah"],
    suitableModels: ["offline", "ruko"],
    suitableAssets: ["bisa komputer", "telaten"],
    riskLevel: "sedang",
    marginRange: [15, 25],
    estimatedPaybackMonth: [4, 9],
    products: [
      { name: "Print B/W (lembar)", sellingPrice: 500, hpp: 200, dailySales: 400 },
      { name: "Print Warna (lembar)", sellingPrice: 1_500, hpp: 600, dailySales: 80 },
      { name: "Jilid Skripsi", sellingPrice: 25_000, hpp: 12_000, dailySales: 3 },
    ],
    capitalItems: [
      { name: "Printer + scanner", amount: 5_000_000 },
      { name: "Stok kertas & tinta", amount: 1_500_000 },
      { name: "Etalase & meja", amount: 1_200_000 },
      { name: "Promosi awal", amount: 300_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Sewa lapak", amount: 1_200_000 },
      { name: "Listrik", amount: 400_000 },
      { name: "Bahan habis pakai", amount: 600_000 },
      { name: "Operator jaga & maintenance printer", amount: 1_500_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "jasa-titip",
    name: "Jasa Titip (Jastip) Belanja",
    category: "Jasa",
    description: "Beli barang dari mall/luar kota untuk pelanggan online.",
    minCapital: 500_000,
    maxCapital: 3_000_000,
    suitableAreas: ["online", "kota besar"],
    suitableModels: ["online", "pre-order"],
    suitableAssets: ["punya hp", "punya kendaraan"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [1, 3],
    products: [
      { name: "Fee Jastip per item", sellingPrice: 25_000, hpp: 5_000, dailySales: 10 },
    ],
    capitalItems: [
      { name: "Modal beli barang awal", amount: 1_000_000 },
      { name: "Promosi awal", amount: 300_000 },
      { name: "Dana cadangan", amount: 500_000 },
    ],
    monthlyCosts: [
      { name: "Bahan bakar / parkir", amount: 400_000 },
      { name: "Marketing online", amount: 200_000 },
      { name: "Waktu belanja, handling & risiko refund", amount: 3_200_000 },
      { name: "Biaya tak terduga", amount: 150_000 },
    ],
  },

  // ───── Beauty ──────────────────────────────────────────────────────────
  {
    id: "beauty-home-salon",
    name: "Home Salon (Hair & Make Up)",
    category: "Beauty",
    description: "Layanan salon panggilan dari rumah untuk hair do dan make up.",
    minCapital: 4_000_000,
    maxCapital: 12_000_000,
    suitableAreas: ["perumahan", "online"],
    suitableModels: ["panggilan", "online", "dari rumah"],
    suitableAssets: ["bisa makeup", "punya alat salon"],
    riskLevel: "sedang",
    marginRange: [15, 25],
    estimatedPaybackMonth: [4, 7],
    products: [
      { name: "Make Up Wisuda/Acara", sellingPrice: 250_000, hpp: 90_000, dailySales: 1 },
      { name: "Hair Do", sellingPrice: 120_000, hpp: 40_000, dailySales: 1 },
    ],
    capitalItems: [
      { name: "Alat make up & sanggul", amount: 3_500_000 },
      { name: "Kosmetik awal", amount: 2_000_000 },
      { name: "Promosi awal", amount: 800_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Transport", amount: 500_000 },
      { name: "Marketing online", amount: 400_000 },
      { name: "Restock kosmetik", amount: 600_000 },
      { name: "Tenaga asisten & penyusutan alat", amount: 2_500_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "beauty-nail-art",
    name: "Nail Art Home Service",
    category: "Beauty",
    description: "Layanan nail art panggilan, target ibu muda dan mahasiswi.",
    minCapital: 2_000_000,
    maxCapital: 6_000_000,
    suitableAreas: ["perumahan", "kampus", "online"],
    suitableModels: ["panggilan", "online", "dari rumah"],
    suitableAssets: ["telaten", "kreatif", "bisa nail art"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [2, 5],
    products: [
      { name: "Nail Art Standar", sellingPrice: 100_000, hpp: 30_000, dailySales: 2 },
      { name: "Nail Art Premium", sellingPrice: 180_000, hpp: 60_000, dailySales: 1 },
    ],
    capitalItems: [
      { name: "Alat nail art lengkap", amount: 1_500_000 },
      { name: "Stok kuteks & ornamen", amount: 1_000_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 800_000 },
    ],
    monthlyCosts: [
      { name: "Transport", amount: 300_000 },
      { name: "Restock bahan", amount: 400_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Tenaga layanan & penyusutan alat", amount: 3_600_000 },
      { name: "Biaya tak terduga", amount: 150_000 },
    ],
  },

  // ───── Laundry ─────────────────────────────────────────────────────────
  {
    id: "laundry-kiloan-mini",
    name: "Laundry Kiloan Mini (Rumahan)",
    category: "Laundry",
    description: "Laundry kiloan area perumahan/kos dengan 2 mesin cuci.",
    minCapital: 8_000_000,
    maxCapital: 18_000_000,
    suitableAreas: ["perumahan", "kos", "kampus"],
    suitableModels: ["offline", "antar-jemput"],
    suitableAssets: ["punya tempat", "telaten"],
    riskLevel: "sedang",
    marginRange: [15, 25],
    estimatedPaybackMonth: [3, 6],
    products: [
      { name: "Cuci Kering Lipat (kg)", sellingPrice: 7_000, hpp: 3_500, dailySales: 60 },
      { name: "Cuci Setrika (kg)", sellingPrice: 9_000, hpp: 4_500, dailySales: 25 },
    ],
    capitalItems: [
      { name: "Mesin cuci 2 unit", amount: 6_000_000 },
      { name: "Setrika & meja setrika", amount: 1_000_000 },
      { name: "Detergent & pewangi awal", amount: 800_000 },
      { name: "Plastik & hanger", amount: 500_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Listrik & air", amount: 1_000_000 },
      { name: "Detergent & pewangi", amount: 800_000 },
      { name: "Sewa tempat", amount: 700_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Operator, jemput-antar & maintenance mesin", amount: 2_300_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "laundry-sepatu-tas",
    name: "Laundry Sepatu & Tas",
    category: "Laundry",
    description: "Cuci sepatu, tas, dan topi sistem antar-jemput.",
    minCapital: 2_500_000,
    maxCapital: 7_000_000,
    suitableAreas: ["perumahan", "kos", "kampus"],
    suitableModels: ["offline", "online", "antar-jemput"],
    suitableAssets: ["telaten", "punya kendaraan"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [1, 3],
    products: [
      { name: "Cuci Sepatu Standar", sellingPrice: 30_000, hpp: 8_000, dailySales: 7 },
      { name: "Cuci Tas", sellingPrice: 45_000, hpp: 12_000, dailySales: 3 },
    ],
    capitalItems: [
      { name: "Peralatan cuci", amount: 1_500_000 },
      { name: "Bahan kimia", amount: 700_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 800_000 },
    ],
    monthlyCosts: [
      { name: "Listrik & air", amount: 300_000 },
      { name: "Bahan habis pakai", amount: 400_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Tenaga operator & antar-jemput", amount: 3_800_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },

  // ───── Digital Product ─────────────────────────────────────────────────
  {
    id: "digital-template-canva",
    name: "Jualan Template Canva / E-book",
    category: "Digital Product",
    description: "Bikin & jual template Canva, e-book, atau preset di marketplace lokal.",
    minCapital: 500_000,
    maxCapital: 3_000_000,
    suitableAreas: ["online"],
    suitableModels: ["online", "marketplace"],
    suitableAssets: ["bisa desain", "bisa nulis", "punya laptop"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [2, 4],
    products: [
      { name: "Template Canva (paket)", sellingPrice: 50_000, hpp: 5_000, dailySales: 2 },
      { name: "E-book digital", sellingPrice: 75_000, hpp: 8_000, dailySales: 0.5 },
    ],
    capitalItems: [
      { name: "Lisensi tools", amount: 600_000 },
      { name: "Promosi awal", amount: 700_000 },
      { name: "Dana cadangan", amount: 700_000 },
    ],
    monthlyCosts: [
      { name: "Subscription tools", amount: 200_000 },
      { name: "Marketing online & ads", amount: 500_000 },
      { name: "Waktu produksi, revisi & support customer", amount: 1_550_000 },
      { name: "Biaya tak terduga", amount: 100_000 },
    ],
  },
  {
    id: "digital-jasa-konten",
    name: "Jasa Konten Sosial Media",
    category: "Digital Product",
    description: "Jasa pembuatan konten Instagram/TikTok bulanan untuk UMKM.",
    minCapital: 1_500_000,
    maxCapital: 5_000_000,
    suitableAreas: ["online"],
    suitableModels: ["online", "freelance"],
    suitableAssets: ["bisa desain", "bisa edit video", "punya laptop"],
    riskLevel: "rendah",
    marginRange: [15, 25],
    estimatedPaybackMonth: [3, 6],
    products: [
      { name: "Paket Konten Bulanan (12 post)", sellingPrice: 750_000, hpp: 150_000, dailySales: 0.2 },
    ],
    capitalItems: [
      { name: "Software desain & video", amount: 800_000 },
      { name: "Stock asset awal", amount: 400_000 },
      { name: "Promosi awal", amount: 700_000 },
      { name: "Dana cadangan", amount: 600_000 },
    ],
    monthlyCosts: [
      { name: "Subscription tools", amount: 350_000 },
      { name: "Marketing online", amount: 400_000 },
      { name: "Waktu produksi & fee freelance support", amount: 1_400_000 },
      { name: "Biaya tak terduga", amount: 150_000 },
    ],
  },

  // ───── Retail ──────────────────────────────────────────────────────────
  {
    id: "retail-warung-sembako",
    name: "Warung Sembako Mini",
    category: "Retail",
    description: "Warung sembako kecil di rumah, target ibu rumah tangga sekitar.",
    minCapital: 5_000_000,
    maxCapital: 15_000_000,
    suitableAreas: ["perumahan", "kompleks"],
    suitableModels: ["offline", "dari rumah"],
    suitableAssets: ["punya tempat", "telaten"],
    riskLevel: "rendah",
    marginRange: [5, 10],
    estimatedPaybackMonth: [4, 8],
    products: [
      { name: "Beras (5kg)", sellingPrice: 65_000, hpp: 58_000, dailySales: 8 },
      { name: "Minyak goreng (1L)", sellingPrice: 16_000, hpp: 14_000, dailySales: 12 },
      { name: "Snack & sembako lain", sellingPrice: 10_000, hpp: 8_000, dailySales: 60 },
    ],
    capitalItems: [
      { name: "Rak & etalase", amount: 1_500_000 },
      { name: "Stok awal sembako", amount: 6_000_000 },
      { name: "Plastik & timbangan", amount: 500_000 },
      { name: "Promosi awal", amount: 300_000 },
      { name: "Dana cadangan", amount: 1_500_000 },
    ],
    monthlyCosts: [
      { name: "Listrik", amount: 200_000 },
      { name: "Sewa tempat / opsional", amount: 500_000 },
      { name: "Plastik & operasional", amount: 200_000 },
      { name: "Susut stok, transport belanja & penjaga", amount: 1_600_000 },
      { name: "Biaya tak terduga", amount: 200_000 },
    ],
  },
  {
    id: "retail-isi-ulang-galon",
    name: "Depot Isi Ulang Galon",
    category: "Retail",
    description: "Depot isi ulang air minum dengan sistem antar gratis.",
    minCapital: 10_000_000,
    maxCapital: 25_000_000,
    suitableAreas: ["perumahan", "kompleks", "kos"],
    suitableModels: ["offline", "antar-jemput"],
    suitableAssets: ["punya tempat", "punya kendaraan"],
    riskLevel: "sedang",
    marginRange: [2, 6],
    estimatedPaybackMonth: [24, 42],
    products: [
      { name: "Galon Isi Ulang", sellingPrice: 6_000, hpp: 2_500, dailySales: 60 },
    ],
    capitalItems: [
      { name: "Mesin filter", amount: 8_000_000 },
      { name: "Galon kosong & kemasan", amount: 2_500_000 },
      { name: "Renovasi tempat", amount: 2_000_000 },
      { name: "Promosi awal", amount: 500_000 },
      { name: "Dana cadangan", amount: 2_000_000 },
    ],
    monthlyCosts: [
      { name: "Listrik", amount: 600_000 },
      { name: "Sewa tempat / opsional", amount: 800_000 },
      { name: "Maintenance filter", amount: 300_000 },
      { name: "Bahan bakar antar", amount: 400_000 },
      { name: "Operator, galon hilang & uji kualitas", amount: 2_700_000 },
      { name: "Biaya tak terduga", amount: 300_000 },
    ],
  },
  {
    id: "retail-pulsa-ppob",
    name: "Konter Pulsa & PPOB",
    category: "Retail",
    description: "Penjualan pulsa, paket data, token listrik, dan pembayaran tagihan.",
    minCapital: 1_500_000,
    maxCapital: 5_000_000,
    suitableAreas: ["perumahan", "kos", "kampus"],
    suitableModels: ["offline", "online", "dari rumah"],
    suitableAssets: ["punya hp", "punya internet"],
    riskLevel: "rendah",
    marginRange: [2, 6],
    estimatedPaybackMonth: [2, 5],
    products: [
      { name: "Pulsa & paket data", sellingPrice: 25_000, hpp: 23_000, dailySales: 30 },
      { name: "Token listrik", sellingPrice: 52_000, hpp: 50_000, dailySales: 15 },
      { name: "Pembayaran tagihan (fee)", sellingPrice: 3_000, hpp: 500, dailySales: 12 },
    ],
    capitalItems: [
      { name: "Saldo deposit awal", amount: 2_000_000 },
      { name: "Etalase kecil", amount: 600_000 },
      { name: "Promosi awal", amount: 300_000 },
      { name: "Dana cadangan", amount: 600_000 },
    ],
    monthlyCosts: [
      { name: "Internet", amount: 200_000 },
      { name: "Listrik", amount: 100_000 },
      { name: "Marketing online", amount: 150_000 },
      { name: "Admin transaksi, selisih saldo & penjaga", amount: 950_000 },
      { name: "Biaya tak terduga", amount: 100_000 },
    ],
  },
  {
    id: "retail-tanaman-hias",
    name: "Tanaman Hias & Pot",
    category: "Retail",
    description: "Jualan tanaman hias dan pot di teras rumah dan online.",
    minCapital: 1_500_000,
    maxCapital: 5_000_000,
    suitableAreas: ["perumahan", "online"],
    suitableModels: ["offline", "online", "dari rumah"],
    suitableAssets: ["suka tanaman", "telaten"],
    riskLevel: "rendah",
    marginRange: [2, 6],
    estimatedPaybackMonth: [8, 12],
    products: [
      { name: "Tanaman hias kecil", sellingPrice: 35_000, hpp: 18_000, dailySales: 6 },
      { name: "Pot keramik", sellingPrice: 25_000, hpp: 12_000, dailySales: 5 },
    ],
    capitalItems: [
      { name: "Stok tanaman & pot", amount: 1_500_000 },
      { name: "Rak & dekorasi", amount: 700_000 },
      { name: "Promosi awal", amount: 400_000 },
      { name: "Dana cadangan", amount: 600_000 },
    ],
    monthlyCosts: [
      { name: "Pupuk & perawatan", amount: 200_000 },
      { name: "Marketing online", amount: 300_000 },
      { name: "Susut tanaman, perawatan harian & display", amount: 3_400_000 },
      { name: "Biaya tak terduga", amount: 100_000 },
    ],
  },
];

export function findTemplateById(id: string) {
  return businessTemplates.find((t) => t.id === id) ?? null;
}
